### ISSUE TITLE
Cannot install your model 

### ISSUE THREAD

**Issue by dwromero** [microljy/DREN#1]
Hello everyone,
when trying to install your model I get this error:

____________

src/caffe/layers/clip_layer.cu(28): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(64): here

src/caffe/layers/clip_layer.cu(29): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(64): here

src/caffe/layers/clip_layer.cu(54): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(64): here

src/caffe/layers/clip_layer.cu(55): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(64): here

src/caffe/layers/clip_layer.cu(28): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(64): here

src/caffe/layers/clip_layer.cu(29): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(64): here

src/caffe/layers/clip_layer.cu(54): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(64): here

src/caffe/layers/clip_layer.cu(55): error: class "caffe::LayerParameter" has no member "clip_param"
          detected during instantiation of "void caffe::ClipLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(64): here

8 errors detected in the compilation of "/tmp/tmpxft_00007776_00000000-11_clip_layer.compute_61.cpp1.ii".
Makefile:604: recipe for target '.build_release/cuda/src/caffe/layers/clip_layer.o' failed

__________________________

Note that I am able to install caffe without problems.

Thanks for your help!

David

**Comment by caiwenchuan008** [comment]
How did you solve the problem?

**Comment by dwromero** [comment]
Hi @caiwenchuan008 
The problem was that the code is no longer compatible with Caffe. I solved it by modifying multiple files in the code. You can find it in the attached link:

`https://drive.google.com/file/d/1Xl0vHfhBe6q9CjVMMiPTiXu599xlmRmh/view?usp=sharing`

Here you will find 2 folders:
```
- caffe-master:  Version that compiles correctly
- DREN-master: Modified DREN code 
```

The preprocessed datasets following the paper are included in the file. To be entirely honest I do not really remember anymore how exactly I made it work but I am pretty sure that the answer is in those 2 folders. I hope that you can execute them directly without problems.

I hope this helps you further :)

Good luck!
David
